theme: jekyll-theme-minimal

title: Puru Tuladhar
description: |> 
  :computer: <code/> <hack/> <aws/>
  :earth_asia: Kathmandu, Nepal

logo: profile.jpg
show_downloads: false
google_analytics: UA-172929172-1

plugins:
  - jemoji
