theme: jekyll-theme-minimal

title: Puru's Personal Website
description: Thank you for visiting my website.

logo: avatar.png
show_downloads: false
google_analytics: [Your Google Analytics tracking ID]

plugins:
  - jemoji
