theme: jekyll-theme-minimal

title: Puru's Personal Website
description: Thank you for visiting my website.

logo: profile.png
show_downloads: false
google_analytics: UA-172929172-1

plugins:
  - jemoji
